### ISSUE TITLE
Failed generation

### ISSUE THREAD

**Issue by harikt** [juzna/apigen-generator#23]
I am not sure why I am seeing a failed generation for Aura.Di .

http://apigen.juzna.cz/doc/auraphp/Aura.Di

**Comment by juzna** [comment]
Yeah, sorry, it was broken. More info in #24

**Comment by harikt** [comment]
Hey @juzna is there a way we can generate from different branches ?

Currently Aura have v1 , v2 for https://github.com/auraphp/Aura.Router . Same for many components. Is there a way for it ?

Thanks!
